// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: location.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Long          float64                `protobuf:"fixed64,1,opt,name=long,proto3" json:"long,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationReq) Reset() {
	*x = LocationReq{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationReq) ProtoMessage() {}

func (x *LocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationReq.ProtoReflect.Descriptor instead.
func (*LocationReq) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationReq) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *LocationReq) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LocationReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LocationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResp) Reset() {
	*x = LocationResp{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResp) ProtoMessage() {}

func (x *LocationResp) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResp.ProtoReflect.Descriptor instead.
func (*LocationResp) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *LocationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LocationResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\blocation\"M\n" +
	"\vLocationReq\x12\x12\n" +
	"\x04long\x18\x01 \x01(\x01R\x04long\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"8\n" +
	"\fLocationResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok2R\n" +
	"\bLocation\x12F\n" +
	"\x13SendLocationAndSave\x12\x15.location.LocationReq\x1a\x16.location.LocationResp\"\x00B\x14Z\x12protobuf/;protobufb\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_location_proto_goTypes = []any{
	(*LocationReq)(nil),  // 0: location.LocationReq
	(*LocationResp)(nil), // 1: location.LocationResp
}
var file_location_proto_depIdxs = []int32{
	0, // 0: location.Location.SendLocationAndSave:input_type -> location.LocationReq
	1, // 1: location.Location.SendLocationAndSave:output_type -> location.LocationResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
